import type { TransformFn } from "@sveltejs/sv-utils"
import { transforms } from "@sveltejs/sv-utils"

export function generateSchema(): TransformFn {
	return transforms.script(({ ast, js, comments }) => {
		const columnType = js.imports.find(ast, {
			from: "kysely",
			name: "ColumnType",
		})
		if (columnType.alias) return false
		ast.body.length = 0

		comments.add(ast, {
			type: "Block",
			value: `*
 * This file was generated by kysely-codegen. Please do not edit it manually.
 *
 * @module
 `,
		})

		js.imports.addNamed(ast, {
			from: "kysely",
			imports: { ColumnType: "ColumnType" },
			isType: true,
		})

		ast.body.push(
			js.common.parseStatement(
				`
export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;
`.trim(),
			),
		)

		ast.body.push(
			js.common.parseStatement(
				`
export interface Task {
	id: Generated<string>;
	priority: Generated<number>;
	title: string;
}
`.trim(),
			),
		)

		ast.body.push(
			js.common.parseStatement(
				`
export interface DB {
	task: Task;
}
`.trim(),
			),
		)

		return
	})
}
